### PR TITLE
Extra metadata doc

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by dsavchenko — APPROVED** [review]

**Review by volodymyrss — APPROVED** [review]
Looks good to me! Let's wait for @ferrigno

**Review by ferrigno — CHANGES_REQUESTED** [review]
This is very useful. 

Suggested change:
 `oda:group`: to visually group together a set of parameters`-  >
 `oda:group`: to visually group together a set of parameters horizontally`

It would be a nice addition to make Vertical "Blocks" of parameters and to control the order of presentation of parameters.

**Comment by burnout87** [comment]
> 
> It would be a nice addition to make Vertical "Blocks" of parameters and to control the order of presentation of parameters.

As for the order, it is actually something already discussed here https://github.com/oda-hub/frontend-tab-generator/issues/25

**Review by ferrigno — APPROVED** [review]

**Comment by dsavchenko** [comment]
> and to control the order of presentation of parameters.

> As for the order, it is actually something already discussed here [oda-hub/frontend-tab-generator#25](https://github.com/oda-hub/frontend-tab-generator/issues/25)

The order is preserved already for quite some time. I closed the corresponding issue.

**Pull request merged**
