### PR TITLE
token annotation examples added to docs

### PR DESCRIPTION
**Pull request by okolo**

### CODE REVIEW

**Review by volodymyrss — APPROVED** [review]
Thanks! At first glance - looks good to me. Let's have @ferrigno assess it as the first immediate user.

**Comment by ferrigno** [comment]
You mention first
from oda_api.api import get_context
token = get_context()['token']

then
from oda_api.token import discover_token
token = discover_token(allow_invalid=True, token_discovery_methods=None)

Are the two codes equivalent? If yes, why you propose two solutions? Which the advantages and drawbacks of one or the other? It is not clear if one needs to set the optional parameters to some values.
You should explain what the options mean an what should be used. It is not clear, sorry.

**Comment by okolo** [comment]
@ferrigno  Indeed both ways described in doc are equivalent, however the second way also provides token validation and token discovery method as extra options as it was stated in the doc. The first way is more low level implementation. I've extended the documentation.

**Comment by ferrigno** [comment]
Can you provide an example of context file so that one can test locally the code and debug ?

**Comment by ferrigno** [comment]
Actually, I would suggest that you drop the option `token_discovery_methods=[oda_api.token.TokenLocation.CONTEXT_FILE]`
because in this way one can run it locally as well as remotely.

**Comment by ferrigno** [comment]
You should add that the annotation enures that the token of the session is stored by the system in a json file called ".oda...."  and then notebook will read it. However, the other methods are suitable to read the token outside of MMODA as in other documentation.

**Review by ferrigno — APPROVED** [review]

**Comment by ferrigno** [comment]
I removed the pre-defined method and explained the usage.

**Pull request merged**
